spring.application.name=joblisting
spring.data.mongodb.uri = mongodb+srv://saisankar:system@cluster0.4xnpdaq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database = cdk
server.port=8080