spring.application.name=joblisting
server.port=8080


# spring.data.mongodb.uri=mongodb+srv://admin:saisankar@cluster0.4xnpdaq.mongodb.net/cdk.joblisting?retryWrites=true&w=majority&appName=Cluster0

#MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=mysql://root:aJKPvbKwGZHGTiqtcOBatKFnpFYTMiTa@metro.proxy.rlwy.net:33294/railway
spring.datasource.username=root
spring.datasource.password=aJKPvbKwGZHGTiqtcOBatKFnpFYTMiTa